### PR TITLE
Optionally use system's boost 

### PR DESCRIPTION
**Pull request by TheAlexHodges**

### CODE REVIEW

**Review by madmongo1 — CHANGES_REQUESTED** [review]
.gitignore update is unnecessary.
You can add a use-wide .gitignore in your come directory and then add a gitconfig entry to process it for every project

**Review by madmongo1 — COMMENTED** [review]
CML change is acceptable.

**Comment by TheAlexHodges** [comment]
@madmongo1 Removed .gitignore + rebased from upstream

**Comment by madmongo1** [comment]
rebased to master

**Pull request closed without merging**
